window.SafeDiveCardLanguagePacks = {
  optionLabels: {
    zh: "🇨🇳 Mandarin-Chinesisch / 中文",
    hi: "🇮🇳 Hindi / हिन्दी",
    es: "🇪🇸 Spanisch / Español",
    fr: "🇫🇷 Französisch / Français",
    pt: "🇵🇹 Portugiesisch / Português",
    id: "🇮🇩 Indonesisch / Bahasa Indonesia",
    ru: "🇷🇺 Russisch / Русский",
    de: "🇩🇪 Deutsch",
    ja: "🇯🇵 Japanisch / 日本語",
    ar: "🇪🇬 Ägyptisches Arabisch / العربية المصرية",
    vi: "🇻🇳 Vietnamesisch / Tiếng Việt",
    tr: "🇹🇷 Türkisch / Türkçe",
    tl: "🇵🇭 Tagalog / Filipino",
    ko: "🇰🇷 Koreanisch / 한국어",
    th: "🇹🇭 Thai / ไทย",
    it: "🇮🇹 Italienisch / Italiano",
    nl: "🇳🇱 Niederländisch / Nederlands",
    pl: "🇵🇱 Polnisch / Polski"
  },
  sex: {
    M: { zh: "男", hi: "पुरुष", pt: "Masculino", id: "Laki-laki", ru: "Мужской", ja: "男性", vi: "Nam", tr: "Erkek", tl: "Lalaki", ko: "남성", th: "ชาย", nl: "Man", pl: "Mężczyzna" },
    F: { zh: "女", hi: "महिला", pt: "Feminino", id: "Perempuan", ru: "Женский", ja: "女性", vi: "Nữ", tr: "Kadın", tl: "Babae", ko: "여성", th: "หญิง", nl: "Vrouw", pl: "Kobieta" },
    X: { zh: "多元", hi: "विविध", pt: "Diverso", id: "Beragam", ru: "Другое", ja: "その他", vi: "Đa dạng", tr: "Çeşitli", tl: "Iba pa", ko: "기타", th: "หลากหลาย", nl: "Divers", pl: "Różnorodne" }
  },
  i18n: {},
  raw: {}
};

Object.assign(window.SafeDiveCardLanguagePacks.i18n, {
  languages_section: {
    zh: "语言",
    hi: "भाषाएँ",
    pt: "Idiomas",
    id: "Bahasa",
    ru: "Языки",
    ja: "言語",
    vi: "Ngôn ngữ",
    tr: "Diller",
    tl: "Mga wika",
    ko: "언어",
    th: "ภาษา",
    nl: "Talen",
    pl: "Języki"
  },
  local_language_label: {
    zh: "本地潜点语言（按潜点国家自动识别，可选覆盖）",
    hi: "स्थानीय डाइव साइट भाषा (डाइव साइट देश के आधार पर स्वतः, वैकल्पिक ओवरराइड)",
    pt: "Idioma local do ponto de mergulho (automático pelo país do local, substituição opcional)",
    id: "Bahasa lokal lokasi selam (otomatis menurut negara lokasi, override opsional)",
    ru: "Локальный язык дайв-сайта (авто по стране сайта, при необходимости переопределить)",
    ja: "ダイブサイトの現地言語（ダイブサイトの国に基づく自動設定、任意で上書き可能）",
    vi: "Ngôn ngữ địa phương của điểm lặn (tự động theo quốc gia điểm lặn, có thể ghi đè)",
    tr: "Yerel dalış noktası dili (dalış noktası ülkesine göre otomatik, isteğe bağlı geçersiz kılma)",
    tl: "Lokal na wika ng dive site (auto ayon sa bansa ng dive site, optional override)",
    ko: "현지 다이브 사이트 언어(다이브 사이트 국가 기준 자동 설정, 선택적 재설정 가능)",
    th: "ภาษาท้องถิ่นของจุดดำน้ำ (อัตโนมัติตามประเทศของจุดดำน้ำ และสามารถ override ได้)",
    nl: "Lokale taal van de duiklocatie (automatisch op basis van land, optionele override)",
    pl: "Lokalny język miejsca nurkowego (automatycznie wg kraju miejsca, opcjonalne nadpisanie)"
  },
  display_language_label: {
    zh: "显示语言 / 可选附加语言",
    hi: "प्रदर्शित भाषा / वैकल्पिक अतिरिक्त भाषा",
    pt: "Idioma de exibição / idioma extra opcional",
    id: "Bahasa tampilan / bahasa tambahan opsional",
    ru: "Язык отображения / дополнительный язык",
    ja: "表示言語 / 任意の追加言語",
    vi: "Ngôn ngữ hiển thị / ngôn ngữ bổ sung tùy chọn",
    tr: "Görüntü dili / isteğe bağlı ek dil",
    tl: "Display language / optional extra language",
    ko: "표시 언어 / 선택적 추가 언어",
    th: "ภาษาที่แสดง / ภาษาเพิ่มเติมแบบเลือกได้",
    nl: "Weergavetaal / optionele extra taal",
    pl: "Język wyświetlania / opcjonalny dodatkowy język"
  },
  no_override_auto: {
    zh: "不覆盖（使用自动本地语言）",
    hi: "कोई ओवरराइड नहीं (स्वतः स्थानीय भाषा का उपयोग करें)",
    pt: "Sem substituição (usar idioma local automático)",
    id: "Tanpa override (gunakan bahasa lokal otomatis)",
    ru: "Без переопределения (использовать авто локальный язык)",
    ja: "上書きなし（自動の現地言語を使用）",
    vi: "Không ghi đè (dùng ngôn ngữ địa phương tự động)",
    tr: "Geçersiz kılma yok (otomatik yerel dili kullan)",
    tl: "Walang override (gamitin ang auto local)",
    ko: "재설정 없음(자동 현지 언어 사용)",
    th: "ไม่ override (ใช้ภาษาท้องถิ่นอัตโนมัติ)",
    nl: "Geen override (gebruik automatische lokale taal)",
    pl: "Bez nadpisania (użyj automatycznego języka lokalnego)"
  },
  continent_europe: { zh: "欧洲", hi: "यूरोप", pt: "Europa", id: "Eropa", ru: "Европа", ja: "ヨーロッパ", vi: "Châu Âu", tr: "Avrupa", tl: "Europe", ko: "유럽", th: "ยุโรป", nl: "Europa", pl: "Europa" },
  continent_africa: { zh: "非洲", hi: "अफ्रीका", pt: "África", id: "Afrika", ru: "Африка", ja: "アフリカ", vi: "Châu Phi", tr: "Afrika", tl: "Africa", ko: "아프리카", th: "แอฟริกา", nl: "Afrika", pl: "Afryka" },
  continent_asia: { zh: "亚洲", hi: "एशिया", pt: "Ásia", id: "Asia", ru: "Азия", ja: "アジア", vi: "Châu Á", tr: "Asya", tl: "Asia", ko: "아시아", th: "เอเชีย", nl: "Azië", pl: "Azja" },
  override_country: {
    zh: "覆盖国家",
    hi: "ओवरराइड देश",
    pt: "País de substituição",
    id: "Negara override",
    ru: "Страна переопределения",
    ja: "上書きする国",
    vi: "Quốc gia ghi đè",
    tr: "Geçersiz kılma ülkesi",
    tl: "Override country",
    ko: "재설정 국가",
    th: "ประเทศที่ใช้ override",
    nl: "Override-land",
    pl: "Kraj nadpisania"
  },
  select_country: {
    zh: "选择国家",
    hi: "देश चुनें",
    pt: "Selecionar país",
    id: "Pilih negara",
    ru: "Выбрать страну",
    ja: "国を選択",
    vi: "Chọn quốc gia",
    tr: "Ülke seç",
    tl: "Pumili ng bansa",
    ko: "국가 선택",
    th: "เลือกประเทศ",
    nl: "Selecteer land",
    pl: "Wybierz kraj"
  },
  none_option: {
    zh: "无",
    hi: "कोई नहीं",
    pt: "Nenhum",
    id: "Tidak ada",
    ru: "Нет",
    ja: "なし",
    vi: "Không",
    tr: "Yok",
    tl: "Wala",
    ko: "없음",
    th: "ไม่มี",
    nl: "Geen",
    pl: "Brak"
  },
  btn_clear: {
    zh: "清空",
    hi: "साफ़ करें",
    pt: "Limpar",
    id: "Kosongkan",
    ru: "Очистить",
    ja: "クリア",
    vi: "Xóa",
    tr: "Temizle",
    tl: "I-clear",
    ko: "지우기",
    th: "ล้างค่า",
    nl: "Leegmaken",
    pl: "Wyczyść"
  }
});

Object.assign(window.SafeDiveCardLanguagePacks.i18n, {
  header_subtitle: {
    zh: "创建一张紧急潜水卡，让潜水更安全。",
    hi: "सुरक्षित डाइव के लिए एक आपातकालीन डाइव कार्ड बनाएं।",
    pt: "Crie um cartão de emergência de mergulho para um mergulho seguro.",
    id: "Buat kartu darurat selam untuk penyelaman yang aman.",
    ru: "Создайте аварийную карточку дайвера для безопасного погружения.",
    ja: "安全なダイビングのための緊急ダイビングカードを作成します。",
    vi: "Tạo thẻ khẩn cấp lặn cho một chuyến lặn an toàn.",
    tr: "Güvenli bir dalış için acil durum dalış kartı oluşturun.",
    tl: "Gumawa ng emergency dive card para sa mas ligtas na pagsisid.",
    ko: "안전한 다이빙을 위한 비상 다이빙 카드를 만드세요.",
    th: "สร้างบัตรฉุกเฉินสำหรับการดำน้ำเพื่อการดำน้ำที่ปลอดภัย",
    nl: "Maak een noodduikkaart voor een veilige duik.",
    pl: "Utwórz kartę awaryjną nurkowania dla bezpiecznego nurkowania."
  },
  input_title: { zh: "输入", hi: "इनपुट", pt: "Entrada", id: "Input", ru: "Ввод", ja: "入力", vi: "Nhập liệu", tr: "Girdi", tl: "Input", ko: "입력", th: "ข้อมูล", nl: "Invoer", pl: "Dane wejściowe" },
  btn_import_json: { zh: "加载潜水数据", hi: "डाइव डेटा लोड करें", pt: "Carregar dados do mergulho", id: "Muat data selam", ru: "Загрузить данные погружения", ja: "ダイブデータを読み込む", vi: "Tải dữ liệu lặn", tr: "Dalış verilerini yükle", tl: "I-load ang dive data", ko: "다이빙 데이터 불러오기", th: "โหลดข้อมูลการดำน้ำ", nl: "Duikgegevens laden", pl: "Wczytaj dane nurkowania" },
  btn_export_json: { zh: "保存潜水数据", hi: "डाइव डेटा सहेजें", pt: "Salvar dados do mergulho", id: "Simpan data selam", ru: "Сохранить данные погружения", ja: "ダイブデータを保存", vi: "Lưu dữ liệu lặn", tr: "Dalış verilerini kaydet", tl: "I-save ang dive data", ko: "다이빙 데이터 저장", th: "บันทึกข้อมูลการดำน้ำ", nl: "Duikgegevens opslaan", pl: "Zapisz dane nurkowania" },
  btn_import_dive_site: { zh: "加载潜点数据", hi: "डाइव साइट डेटा लोड करें", pt: "Carregar dados do local de mergulho", id: "Muat data lokasi selam", ru: "Загрузить данные места погружения", ja: "ダイブサイトデータを読み込む", vi: "Tải dữ liệu điểm lặn", tr: "Dalış noktası verilerini yükle", tl: "I-load ang dive site data", ko: "다이브 사이트 데이터 불러오기", th: "โหลดข้อมูลจุดดำน้ำ", nl: "Duiklocatiegegevens laden", pl: "Wczytaj dane miejsca nurkowego" },
  btn_export_dive_site: { zh: "保存潜点数据", hi: "डाइव साइट डेटा सहेजें", pt: "Salvar dados do local de mergulho", id: "Simpan data lokasi selam", ru: "Сохранить данные места погружения", ja: "ダイブサイトデータを保存", vi: "Lưu dữ liệu điểm lặn", tr: "Dalış noktası verilerini kaydet", tl: "I-save ang dive site data", ko: "다이브 사이트 데이터 저장", th: "บันทึกข้อมูลจุดดำน้ำ", nl: "Duiklocatiegegevens opslaan", pl: "Zapisz dane miejsca nurkowego" },
  btn_import_divers: { zh: "加载潜水员数据", hi: "डाइवर डेटा लोड करें", pt: "Carregar dados do mergulhador", id: "Muat data penyelam", ru: "Загрузить данные дайвера", ja: "ダイバーデータを読み込む", vi: "Tải dữ liệu thợ lặn", tr: "Dalgıç verilerini yükle", tl: "I-load ang diver data", ko: "다이버 데이터 불러오기", th: "โหลดข้อมูลนักดำน้ำ", nl: "Duikergegevens laden", pl: "Wczytaj dane nurka" },
  btn_export_diver: { zh: "保存潜水员数据", hi: "डाइवर डेटा सहेजें", pt: "Salvar dados do mergulhador", id: "Simpan data penyelam", ru: "Сохранить данные дайвера", ja: "ダイバーデータを保存", vi: "Lưu dữ liệu thợ lặn", tr: "Dalgıç verilerini kaydet", tl: "I-save ang diver data", ko: "다이버 데이터 저장", th: "บันทึกข้อมูลนักดำน้ำ", nl: "Duikergegevens opslaan", pl: "Zapisz dane nurka" },
  btn_export_pdf: { zh: "导出 PDF", hi: "PDF निर्यात करें", pt: "Exportar PDF", id: "Ekspor PDF", ru: "Экспорт PDF", ja: "PDF を書き出す", vi: "Xuất PDF", tr: "PDF dışa aktar", tl: "I-export ang PDF", ko: "PDF 내보내기", th: "ส่งออก PDF", nl: "PDF exporteren", pl: "Eksportuj PDF" },
  additional_language: { zh: "附加语言", hi: "अतिरिक्त भाषा", pt: "Idioma adicional", id: "Bahasa tambahan", ru: "Дополнительный язык", ja: "追加言語", vi: "Ngôn ngữ bổ sung", tr: "Ek dil", tl: "Karagdagang wika", ko: "추가 언어", th: "ภาษาเพิ่มเติม", nl: "Extra taal", pl: "Dodatkowy język" },
  dive_site: { zh: "潜点", hi: "डाइव साइट", pt: "Local de mergulho", id: "Lokasi selam", ru: "Место погружения", ja: "ダイブサイト", vi: "Điểm lặn", tr: "Dalış noktası", tl: "Dive site", ko: "다이브 사이트", th: "จุดดำน้ำ", nl: "Duiklocatie", pl: "Miejsce nurkowe" },
  name: { zh: "名称", hi: "नाम", pt: "Nome", id: "Nama", ru: "Название", ja: "名称", vi: "Tên", tr: "Ad", tl: "Pangalan", ko: "이름", th: "ชื่อ", nl: "Naam", pl: "Nazwa" },
  address: { zh: "地址", hi: "पता", pt: "Endereço", id: "Alamat", ru: "Адрес", ja: "住所", vi: "Địa chỉ", tr: "Adres", tl: "Address", ko: "주소", th: "ที่อยู่", nl: "Adres", pl: "Adres" },
  btn_locate_address: { zh: "定位地址", hi: "पता खोजें", pt: "Localizar endereço", id: "Temukan alamat", ru: "Определить адрес", ja: "住所を検索", vi: "Định vị địa chỉ", tr: "Adresi bul", tl: "Hanapin ang address", ko: "주소 찾기", th: "ค้นหาที่อยู่", nl: "Adres zoeken", pl: "Zlokalizuj adres" },
  elevation_m: { zh: "海拔", hi: "ऊंचाई", pt: "Altitude", id: "Ketinggian", ru: "Высота", ja: "標高", vi: "Độ cao", tr: "Rakım", tl: "Taas", ko: "고도", th: "ความสูง", nl: "Hoogte", pl: "Wysokość" },
  latitude_decimal: { zh: "纬度（十进制）", hi: "अक्षांश (दशमलव)", pt: "Latitude (decimal)", id: "Lintang (desimal)", ru: "Широта (десятичная)", ja: "緯度（10進）", vi: "Vĩ độ (thập phân)", tr: "Enlem (ondalık)", tl: "Latitude (decimal)", ko: "위도 (십진수)", th: "ละติจูด (ทศนิยม)", nl: "Breedtegraad (decimaal)", pl: "Szerokość geogr. (dziesiętna)" },
  longitude_decimal: { zh: "经度（十进制）", hi: "देशांतर (दशमलव)", pt: "Longitude (decimal)", id: "Bujur (desimal)", ru: "Долгота (десятичная)", ja: "経度（10進）", vi: "Kinh độ (thập phân)", tr: "Boylam (ondalık)", tl: "Longitude (decimal)", ko: "경도 (십진수)", th: "ลองจิจูด (ทศนิยม)", nl: "Lengtegraad (decimaal)", pl: "Długość geogr. (dziesiętna)" }
});

Object.assign(window.SafeDiveCardLanguagePacks.i18n, {
  dive_base_phone: { zh: "潜店电话", hi: "डाइव बेस फोन", pt: "Telefone da base de mergulho", id: "Telepon basis selam", ru: "Телефон дайв-базы", ja: "ダイブベースの電話", vi: "Điện thoại trung tâm lặn", tr: "Dalış merkezi telefonu", tl: "Telepono ng dive base", ko: "다이브 베이스 전화", th: "โทรศัพท์ศูนย์ดำน้ำ", nl: "Telefoon duikbasis", pl: "Telefon bazy nurkowej" },
  dive_base_website: { zh: "潜店网站", hi: "डाइव बेस वेबसाइट", pt: "Site da base de mergulho", id: "Situs basis selam", ru: "Сайт дайв-базы", ja: "ダイブベースのウェブサイト", vi: "Trang web trung tâm lặn", tr: "Dalış merkezi web sitesi", tl: "Website ng dive base", ko: "다이브 베이스 웹사이트", th: "เว็บไซต์ศูนย์ดำน้ำ", nl: "Website duikbasis", pl: "Strona bazy nurkowej" },
  oxygen_location: { zh: "氧气位置", hi: "ऑक्सीजन का स्थान", pt: "Local do oxigênio", id: "Lokasi oksigen", ru: "Место кислорода", ja: "酸素の場所", vi: "Vị trí oxy", tr: "Oksijen konumu", tl: "Lokasyon ng oxygen", ko: "산소 위치", th: "ตำแหน่งออกซิเจน", nl: "Locatie zuurstof", pl: "Lokalizacja tlenu" },
  local_emergency_number: { zh: "当地紧急电话", hi: "स्थानीय आपातकालीन नंबर", pt: "Número local de emergência", id: "Nomor darurat lokal", ru: "Местный экстренный номер", ja: "現地の緊急番号", vi: "Số khẩn cấp địa phương", tr: "Yerel acil numara", tl: "Lokal na emergency number", ko: "현지 긴급번호", th: "หมายเลขฉุกเฉินท้องถิ่น", nl: "Lokaal noodnummer", pl: "Lokalny numer alarmowy" },
  emergency_number_hospital: { zh: "紧急电话 / 医院", hi: "आपातकालीन नंबर / अस्पताल", pt: "Número de emergência / Hospital", id: "Nomor darurat / Rumah sakit", ru: "Экстренный номер / Больница", ja: "緊急番号 / 病院", vi: "Số khẩn cấp / Bệnh viện", tr: "Acil numara / Hastane", tl: "Emergency number / Ospital", ko: "긴급번호 / 병원", th: "หมายเลขฉุกเฉิน / โรงพยาบาล", nl: "Noodnummer / Ziekenhuis", pl: "Numer alarmowy / Szpital" },
  hospital_info: { zh: "急诊医院（名称和地址）", hi: "आपातकालीन अस्पताल (नाम और पता)", pt: "Hospital de emergência (nome e endereço)", id: "Rumah sakit darurat (nama dan alamat)", ru: "Экстренная больница (название и адрес)", ja: "救急病院（名称と住所）", vi: "Bệnh viện cấp cứu (tên và địa chỉ)", tr: "Acil hastane (ad ve adres)", tl: "Emergency hospital (pangalan at address)", ko: "응급 병원(이름 및 주소)", th: "โรงพยาบาลฉุกเฉิน (ชื่อและที่อยู่)", nl: "Spoedziekenhuis (naam en adres)", pl: "Szpital ratunkowy (nazwa i adres)" },
  hospital: { zh: "医院", hi: "अस्पताल", pt: "Hospital", id: "Rumah sakit", ru: "Больница", ja: "病院", vi: "Bệnh viện", tr: "Hastane", tl: "Ospital", ko: "병원", th: "โรงพยาบาล", nl: "Ziekenhuis", pl: "Szpital" },
  emergency_phone_location: { zh: "应急电话位置", hi: "आपातकालीन फोन का स्थान", pt: "Local do telefone de emergência", id: "Lokasi telepon darurat", ru: "Место аварийного телефона", ja: "緊急電話の場所", vi: "Vị trí điện thoại khẩn cấp", tr: "Acil telefon konumu", tl: "Lokasyon ng emergency phone", ko: "비상 전화 위치", th: "ตำแหน่งโทรศัพท์ฉุกเฉิน", nl: "Locatie noodtelefoon", pl: "Lokalizacja telefonu alarmowego" },
  chamber_info: { zh: "高压氧舱信息（地址和紧急联系电话）", hi: "हाइपरबेरिक चैंबर जानकारी (पता और आपात फोन)", pt: "Informações da câmara hiperbárica (endereço e telefone de emergência)", id: "Informasi kamar hiperbarik (alamat dan telepon darurat)", ru: "Информация о барокамере (адрес и экстренный телефон)", ja: "高圧酸素チャンバー情報（住所と緊急連絡先）", vi: "Thông tin buồng cao áp (địa chỉ và số điện thoại khẩn cấp)", tr: "Hiperbarik oda bilgisi (adres ve acil telefon)", tl: "Impormasyon ng hyperbaric chamber (address at emergency phone)", ko: "고압 챔버 정보(주소 및 비상 연락처)", th: "ข้อมูลห้องปรับความดัน (ที่อยู่และโทรศัพท์ฉุกเฉิน)", nl: "Hyperbare kamer informatie (adres en noodtelefoon)", pl: "Informacje o komorze hiperbarycznej (adres i telefon alarmowy)" },
  dive_plan: { zh: "潜水计划", hi: "डाइव योजना", pt: "Plano de mergulho", id: "Rencana selam", ru: "План погружения", ja: "ダイブプラン", vi: "Kế hoạch lặn", tr: "Dalış planı", tl: "Dive plan", ko: "다이빙 계획", th: "แผนการดำน้ำ", nl: "Duikplan", pl: "Plan nurkowania" },
  summary: { zh: "潜水计划摘要（例如：天数、每天计划潜水次数、特殊情况）", hi: "डाइव योजना सारांश (जैसे: दिनों की संख्या, प्रति दिन डाइव, विशेष स्थितियाँ)", pt: "Resumo do plano de mergulho (por exemplo: número de dias, mergulhos por dia, condições especiais)", id: "Ringkasan rencana selam (misalnya: jumlah hari, rencana penyelaman per hari, kondisi khusus)", ru: "Краткое описание плана погружения (например: число дней, погружений в день, особые условия)", ja: "ダイブ計画の概要（例：日数、1日の予定本数、特別な条件）", vi: "Tóm tắt kế hoạch lặn (ví dụ: số ngày, số lần lặn mỗi ngày, điều kiện đặc biệt)", tr: "Dalış planı özeti (örneğin: gün sayısı, günde planlanan dalış sayısı, özel koşullar)", tl: "Buod ng dive plan (halimbawa: bilang ng araw, planong dives bawat araw, espesyal na kondisyon)", ko: "다이빙 계획 요약(예: 일수, 하루 예정 다이빙 횟수, 특수 조건)", th: "สรุปแผนการดำน้ำ (เช่น จำนวนวัน จำนวนไดฟ์ต่อวัน เงื่อนไขพิเศษ)", nl: "Samenvatting duikplan (bijv. aantal dagen, geplande duiken per dag, bijzondere omstandigheden)", pl: "Podsumowanie planu nurkowania (np. liczba dni, planowane nurkowania dziennie, szczególne warunki)" },
  max_depth_m: { zh: "最大深度", hi: "अधिकतम गहराई", pt: "Profundidade máxima", id: "Kedalaman maksimum", ru: "Макс. глубина", ja: "最大深度", vi: "Độ sâu tối đa", tr: "Maksimum derinlik", tl: "Max depth", ko: "최대 수심", th: "ความลึกสูงสุด", nl: "Maximale diepte", pl: "Maksymalna głębokość" },
  divers: { zh: "潜水员", hi: "डाइवर्स", pt: "Mergulhadores", id: "Penyelam", ru: "Дайверы", ja: "ダイバー", vi: "Thợ lặn", tr: "Dalgıçlar", tl: "Mga diver", ko: "다이버", th: "นักดำน้ำ", nl: "Duikers", pl: "Nurkowie" },
  btn_add_diver: { zh: "添加潜水员", hi: "डाइवर जोड़ें", pt: "Adicionar mergulhador", id: "Tambah penyelam", ru: "Добавить дайвера", ja: "ダイバーを追加", vi: "Thêm thợ lặn", tr: "Dalgıç ekle", tl: "Magdagdag ng diver", ko: "다이버 추가", th: "เพิ่มนักดำน้ำ", nl: "Duiker toevoegen", pl: "Dodaj nurka" },
  card_preview: { zh: "卡片预览", hi: "कार्ड पूर्वावलोकन", pt: "Pré-visualização do cartão", id: "Pratinjau kartu", ru: "Предпросмотр карты", ja: "カードプレビュー", vi: "Xem trước thẻ", tr: "Kart önizleme", tl: "Preview ng card", ko: "카드 미리보기", th: "ตัวอย่างบัตร", nl: "Kaartvoorbeeld", pl: "Podgląd karty" },
  card_title: { zh: "紧急卡", hi: "आपातकालीन कार्ड", pt: "CARTÃO DE EMERGÊNCIA", id: "KARTU DARURAT", ru: "КАРТОЧКА ЧС", ja: "緊急カード", vi: "THẺ KHẨN CẤP", tr: "ACİL DURUM KARTI", tl: "EMERGENCY CARD", ko: "비상 카드", th: "บัตรฉุกเฉิน", nl: "NOODKAART", pl: "KARTA AWARYJNA" }
});

Object.assign(window.SafeDiveCardLanguagePacks.i18n, {
  where: { zh: "地点", hi: "कहाँ", pt: "Onde", id: "Di mana", ru: "Где", ja: "場所", vi: "Ở đâu", tr: "Nerede", tl: "Saan", ko: "어디", th: "ที่ไหน", nl: "Waar", pl: "Gdzie" },
  what: { zh: "内容", hi: "क्या", pt: "O quê", id: "Apa", ru: "Что", ja: "内容", vi: "Cái gì", tr: "Ne", tl: "Ano", ko: "무엇", th: "อะไร", nl: "Wat", pl: "Co" },
  who: { zh: "人员", hi: "कौन", pt: "Quem", id: "Siapa", ru: "Кто", ja: "誰", vi: "Ai", tr: "Kim", tl: "Sino", ko: "누구", th: "ใคร", nl: "Wie", pl: "Kto" },
  site: { zh: "地点", hi: "स्थल", pt: "Local", id: "Lokasi", ru: "Место", ja: "場所", vi: "Điểm", tr: "Yer", tl: "Lugar", ko: "장소", th: "สถานที่", nl: "Locatie", pl: "Miejsce" },
  coordinates: { zh: "坐标", hi: "निर्देशांक", pt: "Coordenadas", id: "Koordinat", ru: "Координаты", ja: "座標", vi: "Tọa độ", tr: "Koordinatlar", tl: "Coordinates", ko: "좌표", th: "พิกัด", nl: "Coördinaten", pl: "Współrzędne" },
  plan: { zh: "计划", hi: "योजना", pt: "Plano", id: "Rencana", ru: "План", ja: "計画", vi: "Kế hoạch", tr: "Plan", tl: "Plano", ko: "계획", th: "แผน", nl: "Plan", pl: "Plan" },
  max_depth: { zh: "最大深度", hi: "अधिकतम गहराई", pt: "Prof. máxima", id: "Kedalaman maks.", ru: "Макс. глубина", ja: "最大深度", vi: "Độ sâu tối đa", tr: "Maks. derinlik", tl: "Max depth", ko: "최대 수심", th: "ความลึกสูงสุด", nl: "Max. diepte", pl: "Maks. głębokość" },
  sex: { zh: "性别", hi: "लिंग", pt: "Sexo", id: "Jenis kelamin", ru: "Пол", ja: "性別", vi: "Giới tính", tr: "Cinsiyet", tl: "Kasarian", ko: "성별", th: "เพศ", nl: "Geslacht", pl: "Płeć" },
  birth: { zh: "出生", hi: "जन्म", pt: "Nascimento", id: "Lahir", ru: "Рождение", ja: "生年月日", vi: "Sinh", tr: "Doğum", tl: "Kapanganakan", ko: "출생", th: "เกิด", nl: "Geboorte", pl: "Urodzenie" },
  dives: { zh: "潜水次数", hi: "डाइव्स", pt: "Mergulhos", id: "Penyelaman", ru: "Погружения", ja: "本数", vi: "Lần lặn", tr: "Dalışlar", tl: "Mga dive", ko: "다이빙 횟수", th: "จำนวนไดฟ์", nl: "Duiken", pl: "Nurkowania" },
  certifications: { zh: "认证", hi: "प्रमाणपत्र", pt: "Certificações", id: "Sertifikasi", ru: "Сертификации", ja: "資格", vi: "Chứng chỉ", tr: "Sertifikalar", tl: "Sertipikasyon", ko: "자격증", th: "ใบรับรอง", nl: "Certificeringen", pl: "Certyfikaty" },
  gas: { zh: "气体", hi: "गैस", pt: "Gás", id: "Gas", ru: "Газ", ja: "ガス", vi: "Khí", tr: "Gaz", tl: "Gas", ko: "가스", th: "แก๊ส", nl: "Gas", pl: "Gaz" },
  allergies: { zh: "过敏", hi: "एलर्जी", pt: "Alergias", id: "Alergi", ru: "Аллергии", ja: "アレルギー", vi: "Dị ứng", tr: "Alerjiler", tl: "Allergy", ko: "알레르기", th: "อาการแพ้", nl: "Allergieën", pl: "Alergie" },
  conditions: { zh: "病史", hi: "चिकित्सीय स्थितियाँ", pt: "Condições médicas", id: "Kondisi medis", ru: "Медицинские состояния", ja: "既往症", vi: "Tình trạng y tế", tr: "Tıbbi durumlar", tl: "Kondisyong medikal", ko: "의학적 상태", th: "โรคประจำตัว", nl: "Medische aandoeningen", pl: "Choroby przewlekłe" },
  medications: { zh: "药物", hi: "दवाएँ", pt: "Medicamentos", id: "Obat-obatan", ru: "Лекарства", ja: "服用薬", vi: "Thuốc", tr: "İlaçlar", tl: "Gamot", ko: "복용약", th: "ยา", nl: "Medicatie", pl: "Leki" },
  health_ins: { zh: "医疗保险提供方", hi: "स्वास्थ्य बीमा प्रदाता", pt: "Seguradora de saúde", id: "Penyedia asuransi kesehatan", ru: "Поставщик медстраховки", ja: "健康保険会社", vi: "Nhà cung cấp bảo hiểm y tế", tr: "Sağlık sigortası sağlayıcısı", tl: "Provider ng health insurance", ko: "건강보험 제공자", th: "ผู้ให้บริการประกันสุขภาพ", nl: "Zorgverzekeraar", pl: "Ubezpieczyciel zdrowotny" },
  hyperbaric_chamber: { zh: "高压氧舱", hi: "हाइपरबेरिक चैंबर", pt: "Câmara hiperbárica", id: "Kamar hiperbarik", ru: "Барокамера", ja: "高圧チャンバー", vi: "Buồng cao áp", tr: "Hiperbarik oda", tl: "Hyperbaric chamber", ko: "고압 챔버", th: "ห้องปรับความดัน", nl: "Hyperbare kamer", pl: "Komora hiperbaryczna" },
  dive_ins: { zh: "潜水保险", hi: "डाइव बीमा", pt: "Seguro mergulho", id: "Asuransi selam", ru: "Страховка дайвера", ja: "ダイビング保険", vi: "Bảo hiểm lặn", tr: "Dalış sigortası", tl: "Dive insurance", ko: "다이빙 보험", th: "ประกันดำน้ำ", nl: "Duikverzekering", pl: "Ubezp. nurkowe" },
  member_no: { zh: "会员号", hi: "सदस्य संख्या", pt: "N.º de membro", id: "No. anggota", ru: "Номер участника", ja: "会員番号", vi: "Số thành viên", tr: "Üye no", tl: "Member no.", ko: "회원 번호", th: "หมายเลขสมาชิก", nl: "Lidnummer", pl: "Nr członka" },
  hotline: { zh: "热线", hi: "हॉटलाइन", pt: "Hotline", id: "Hotline", ru: "Горячая линия", ja: "ホットライン", vi: "Đường dây nóng", tr: "Hat", tl: "Hotline", ko: "핫라인", th: "สายด่วน", nl: "Hotline", pl: "Infolinia" },
  emergency_contact: { zh: "紧急联系人", hi: "आपातकालीन संपर्क", pt: "Contato de emergência", id: "Kontak darurat", ru: "Экстренный контакт", ja: "緊急連絡先", vi: "Liên hệ khẩn cấp", tr: "Acil durum kişisi", tl: "Emergency contact", ko: "비상 연락처", th: "ผู้ติดต่อฉุกเฉิน", nl: "Noodcontact", pl: "Kontakt alarmowy" },
  own_phone: { zh: "本人电话", hi: "अपना फोन", pt: "Telefone próprio", id: "Telepon sendiri", ru: "Свой телефон", ja: "本人の電話", vi: "Điện thoại của mình", tr: "Kendi telefonu", tl: "Sariling telepono", ko: "본인 전화", th: "โทรศัพท์ของตนเอง", nl: "Eigen telefoon", pl: "Własny telefon" },
  not_provided: { zh: "未提供", hi: "उपलब्ध नहीं", pt: "Não informado", id: "Tidak tersedia", ru: "Не указано", ja: "未提供", vi: "Chưa cung cấp", tr: "Belirtilmedi", tl: "Hindi ibinigay", ko: "제공되지 않음", th: "ไม่ได้ระบุ", nl: "Niet opgegeven", pl: "Nie podano" },
  no_map_data: { zh: "没有用于地图预览的地址/坐标。", hi: "मानचित्र पूर्वावलोकन के लिए पता/निर्देशांक उपलब्ध नहीं हैं।", pt: "Sem endereço/coordenadas para a pré-visualização do mapa.", id: "Tidak ada alamat/koordinat untuk pratinjau peta.", ru: "Нет адреса/координат для предпросмотра карты.", ja: "地図プレビュー用の住所/座標がありません。", vi: "Không có địa chỉ/tọa độ để xem trước bản đồ.", tr: "Harita önizlemesi için adres/koordinat yok.", tl: "Walang address/coordinates para sa map preview.", ko: "지도 미리보기에 사용할 주소/좌표가 없습니다.", th: "ไม่มีที่อยู่/พิกัดสำหรับตัวอย่างแผนที่", nl: "Geen adres/coördinaten voor kaartvoorbeeld.", pl: "Brak adresu/współrzędnych do podglądu mapy." },
  open_large_map: { zh: "打开大地图", hi: "बड़ा मानचित्र खोलें", pt: "Abrir mapa maior", id: "Buka peta besar", ru: "Открыть большую карту", ja: "大きな地図を開く", vi: "Mở bản đồ lớn", tr: "Büyük haritayı aç", tl: "Buksan ang malaking mapa", ko: "큰 지도 열기", th: "เปิดแผนที่ขนาดใหญ่", nl: "Grotere kaart openen", pl: "Otwórz większą mapę" },
  open_search_map: { zh: "打开搜索地图", hi: "खोज मानचित्र खोलें", pt: "Abrir mapa de busca", id: "Buka peta pencarian", ru: "Открыть карту поиска", ja: "検索マップを開く", vi: "Mở bản đồ tìm kiếm", tr: "Arama haritasını aç", tl: "Buksan ang search map", ko: "검색 지도 열기", th: "เปิดแผนที่ค้นหา", nl: "Zoekkaart openen", pl: "Otwórz mapę wyszukiwania" },
  precise_marker_hint: { zh: "使用“定位地址”获取精确标记。", hi: "सटीक मार्कर के लिए \"Locate Address\" का उपयोग करें।", pt: "use \"Localizar endereço\" para um marcador preciso.", id: "gunakan \"Temukan alamat\" untuk penanda yang akurat.", ru: "используйте \"Определить адрес\" для точной отметки.", ja: "正確なマーカーには「住所を検索」を使用してください。", vi: "dùng \"Định vị địa chỉ\" để có điểm đánh dấu chính xác.", tr: "tam işaret için \"Adresi bul\" kullanın.", tl: "gamitin ang \"Hanapin ang address\" para sa eksaktong marker.", ko: "정확한 마커를 위해 \"주소 찾기\"를 사용하세요.", th: "ใช้ \"ค้นหาที่อยู่\" เพื่อให้ได้ตำแหน่งที่แม่นยำ", nl: "gebruik \"Adres zoeken\" voor een exacte markering.", pl: "użyj „Zlokalizuj adres”, aby uzyskać dokładny znacznik." }
});

Object.assign(window.SafeDiveCardLanguagePacks.i18n, {
  altitude_dive_note: {
    zh: "高于 300 米时，这被视为高海拔潜水。请使用高海拔潜水减压表，并确保你的潜水电脑已正确设置。",
    hi: "300 मीटर से ऊपर इसे ऊँचाई पर की जाने वाली डाइव माना जाता है। ऊँचाई वाली डाइव की डेको तालिकाएँ उपयोग करें और सुनिश्चित करें कि आपका डाइव कंप्यूटर सही तरीके से सेट है।",
    pt: "Acima de 300 m isso é considerado um mergulho em altitude. Use as tabelas de descompressão para altitude e certifique-se de que o computador de mergulho esteja configurado corretamente.",
    id: "Di atas 300 m ini dianggap sebagai penyelaman ketinggian. Gunakan tabel deko penyelaman ketinggian dan pastikan komputer selam Anda diatur dengan benar.",
    ru: "Выше 300 м это считается высокогорным погружением. Используйте таблицы декомпрессии для высокогорных погружений и убедитесь, что ваш дайв-компьютер настроен правильно.",
    ja: "300 m を超える場合、これは高所ダイビングと見なされます。高所ダイビング用の減圧テーブルを使用し、ダイブコンピューターが正しく設定されていることを確認してください。",
    vi: "Trên 300 m, đây được xem là lặn ở độ cao. Hãy sử dụng bảng giải nén cho lặn độ cao và bảo đảm máy tính lặn được cài đặt đúng.",
    tr: "300 m üzerinde bu bir irtifa dalışı olarak kabul edilir. İrtifa dalışı deko tablolarını kullanın ve dalış bilgisayarınızın buna göre ayarlandığından emin olun.",
    tl: "Kapag lampas 300 m, itinuturing itong altitude dive. Gamitin ang altitude dive deco tables at tiyaking naka-set nang tama ang dive computer mo.",
    ko: "300m 이상에서는 고지대 다이빙으로 간주됩니다. 고지대 감압표를 사용하고 다이빙 컴퓨터가 올바르게 설정되어 있는지 확인하세요.",
    th: "หากสูงกว่า 300 เมตร ให้ถือว่าเป็นการดำน้ำในที่สูง ใช้ตารางดีคอมเพรสชันสำหรับการดำน้ำในที่สูง และตรวจสอบให้แน่ใจว่าตั้งค่าคอมพิวเตอร์ดำน้ำถูกต้องแล้ว",
    nl: "Boven 300 m wordt dit beschouwd als een hoogte-duik. Gebruik hoogte-duikdecompressietabellen en zorg dat je duikcomputer correct is ingesteld.",
    pl: "Powyżej 300 m jest to nurkowanie wysokogórskie. Użyj tabel dekompresyjnych dla nurkowań wysokogórskich i upewnij się, że komputer nurkowy jest odpowiednio ustawiony."
  },
  locate_address_hint: {
    zh: "纬度/经度和大致海拔可通过“定位地址”自动填写。",
    hi: "अक्षांश/देशांतर और अनुमानित ऊँचाई को Locate Address के माध्यम से स्वतः भरा जा सकता है।",
    pt: "Latitude/longitude e altitude aproximada podem ser preenchidas automaticamente via Localizar endereço.",
    id: "Lintang/bujur dan perkiraan ketinggian dapat diisi otomatis melalui Temukan alamat.",
    ru: "Широта/долгота и примерная высота могут быть автоматически заполнены через функцию поиска адреса.",
    ja: "緯度・経度とおおよその標高は「住所を検索」で自動入力できます。",
    vi: "Vĩ độ/kinh độ và độ cao gần đúng có thể được điền tự động qua chức năng định vị địa chỉ.",
    tr: "Enlem/boylam ve yaklaşık rakım, Adresi bul ile otomatik doldurulabilir.",
    tl: "Puwedeng awtomatikong punan ang latitude/longitude at tinatayang taas gamit ang Hanapin ang address.",
    ko: "위도/경도와 대략적인 고도는 주소 찾기를 통해 자동 입력할 수 있습니다.",
    th: "ละติจูด/ลองจิจูดและความสูงโดยประมาณสามารถกรอกอัตโนมัติได้ผ่าน ค้นหาที่อยู่",
    nl: "Breedte-/lengtegraad en een ruwe hoogte kunnen automatisch worden ingevuld via Adres zoeken.",
    pl: "Szerokość/długość geograficzna oraz przybliżona wysokość mogą zostać uzupełnione automatycznie przez Zlokalizuj adres."
  },
  divers_in_group_label: {
    zh: "团队潜水员人数",
    hi: "समूह में डाइवर्स",
    pt: "Mergulhadores no grupo",
    id: "Penyelam dalam grup",
    ru: "Дайверов в группе",
    ja: "グループのダイバー数",
    vi: "Số thợ lặn trong nhóm",
    tr: "Gruptaki dalgıç sayısı",
    tl: "Mga diver sa grupo",
    ko: "그룹 내 다이버 수",
    th: "นักดำน้ำในกลุ่ม",
    nl: "Duikers in de groep",
    pl: "Nurkowie w grupie"
  },
  map_title: { zh: "地图", hi: "मानचित्र", pt: "Mapa", id: "Peta", ru: "Карта", ja: "地図", vi: "Bản đồ", tr: "Harita", tl: "Mapa", ko: "지도", th: "แผนที่", nl: "Kaart", pl: "Mapa" },
  export_title: { zh: "导出", hi: "निर्यात", pt: "Exportar", id: "Ekspor", ru: "Экспорт", ja: "書き出し", vi: "Xuất", tr: "Dışa aktar", tl: "Export", ko: "내보내기", th: "ส่งออก", nl: "Export", pl: "Eksport" },
  export_warning: {
    zh: "请确保在潜水前通过电子邮件或 WhatsApp 将此 PDF 的电子版发送给你的潜伴。同时，建议将打印版放入 DIN A4 防水地图袋并带到潜点。",
    hi: "डाइव से पहले इस PDF की डिजिटल कॉपी अपने डाइव साथियों को ईमेल या WhatsApp से भेजना सुनिश्चित करें। साथ ही, DIN A4 ड्राई मैप केस में एक प्रिंटेड कॉपी डाइव साइट पर ले जाना भी उचित है।",
    pt: "Certifique-se de enviar uma cópia digital deste PDF aos seus companheiros de mergulho por e-mail ou WhatsApp antes do mergulho. Também é uma boa ideia levar uma versão impressa em um dry map case DIN A4 para o ponto de mergulho.",
    id: "Pastikan Anda mengirim salinan digital PDF ini kepada buddy selam Anda melalui email atau WhatsApp sebelum penyelaman. Sebaiknya juga membawa versi cetak dalam dry map case DIN A4 ke lokasi selam.",
    ru: "Обязательно отправьте цифровую копию этого PDF своим напарникам по дайвингу по электронной почте или через WhatsApp до погружения. Также рекомендуется взять распечатанную версию в водозащитном чехле формата DIN A4 на место погружения.",
    ja: "ダイビング前に、この PDF のデジタルコピーをメールまたは WhatsApp でバディに送ってください。また、DIN A4 の防水マップケースに入れた印刷版をダイブサイトに持参することもおすすめします。",
    vi: "Hãy nhớ gửi bản sao kỹ thuật số của PDF này cho bạn lặn qua email hoặc WhatsApp trước khi lặn. Đồng thời, bạn cũng nên mang theo một bản in trong túi chống nước DIN A4 đến điểm lặn.",
    tr: "Dalıştan önce bu PDF'nin dijital bir kopyasını dalış arkadaşlarınıza e-posta veya WhatsApp ile göndermeyi unutmayın. Ayrıca dalış noktasına DIN A4 dry map case içinde basılı bir kopya götürmeniz de iyi bir fikirdir.",
    tl: "Siguraduhing magpadala ng digital na kopya ng PDF na ito sa iyong dive buddies sa pamamagitan ng email o WhatsApp bago ang dive. Mainam ding magdala ng naka-print na bersyon sa isang DIN A4 dry map case papunta sa dive spot.",
    ko: "다이빙 전에 이 PDF의 디지털 사본을 이메일이나 WhatsApp으로 다이빙 버디에게 보내세요. 또한 DIN A4 드라이 맵 케이스에 넣은 인쇄본을 다이브 포인트에 가져가는 것도 좋습니다.",
    th: "โปรดส่งสำเนา PDF นี้แบบดิจิทัลให้บัดดี้ดำน้ำของคุณทางอีเมลหรือ WhatsApp ก่อนดำน้ำ และควรพกฉบับพิมพ์ใส่ซองกันน้ำ DIN A4 ไปยังจุดดำน้ำด้วย",
    nl: "Zorg ervoor dat je vóór de duik een digitale kopie van deze PDF naar je duikbuddy's stuurt via e-mail of WhatsApp. Het is ook verstandig om een geprinte versie in een DIN A4 dry map case mee te nemen naar de duiklocatie.",
    pl: "Pamiętaj, aby przed nurkowaniem wysłać cyfrową kopię tego pliku PDF swoim partnerom nurkowym e-mailem lub przez WhatsApp. Warto też zabrać wydrukowaną wersję w wodoodpornym etui DIN A4 na miejsce nurkowe."
  },
  deco_beer_title: {
    zh: "感谢使用 SafeDiveCard",
    hi: "SafeDiveCard उपयोग करने के लिए धन्यवाद",
    pt: "Obrigado por usar o SafeDiveCard",
    id: "Terima kasih telah menggunakan SafeDiveCard",
    ru: "Спасибо за использование SafeDiveCard",
    ja: "SafeDiveCard をご利用いただきありがとうございます",
    vi: "Cảm ơn bạn đã sử dụng SafeDiveCard",
    tr: "SafeDiveCard kullandığınız için teşekkür ederiz",
    tl: "Salamat sa paggamit ng SafeDiveCard",
    ko: "SafeDiveCard를 사용해 주셔서 감사합니다",
    th: "ขอบคุณที่ใช้ SafeDiveCard",
    nl: "Bedankt voor het gebruiken van SafeDiveCard",
    pl: "Dziękujemy za korzystanie z SafeDiveCard"
  },
  deco_beer_message: {
    zh: "感谢使用此工具。创建并分享你的紧急卡，是迈向更安全潜水的第一重要步骤。",
    hi: "इस टूल का उपयोग करने के लिए धन्यवाद। अपनी आपातकालीन कार्ड बनाना और साझा करना अधिक सुरक्षित डाइव की दिशा में पहला महत्वपूर्ण कदम है।",
    pt: "Obrigado por usar a ferramenta. Criar e compartilhar seu cartão de emergência é o primeiro passo importante para um mergulho mais seguro.",
    id: "Terima kasih telah menggunakan alat ini. Membuat dan membagikan kartu darurat Anda adalah langkah penting pertama menuju penyelaman yang lebih aman.",
    ru: "Спасибо за использование инструмента. Создание и распространение вашей аварийной карточки — это первый важный шаг к более безопасному погружению.",
    ja: "このツールをご利用いただきありがとうございます。緊急カードを作成して共有することは、より安全なダイビングに向けた最初の重要な一歩です。",
    vi: "Cảm ơn bạn đã sử dụng công cụ này. Việc tạo và chia sẻ thẻ khẩn cấp là bước quan trọng đầu tiên hướng tới một chuyến lặn an toàn hơn.",
    tr: "Aracı kullandığınız için teşekkür ederiz. Acil durum kartınızı oluşturmak ve paylaşmak daha güvenli bir dalış için ilk önemli adımdır.",
    tl: "Salamat sa paggamit ng tool. Ang paggawa at pagbabahagi ng iyong emergency card ang unang mahalagang hakbang tungo sa mas ligtas na pagsisid.",
    ko: "도구를 사용해 주셔서 감사합니다. 비상 카드를 만들고 공유하는 것은 더 안전한 다이빙을 위한 첫 번째 중요한 단계입니다.",
    th: "ขอบคุณที่ใช้เครื่องมือนี้ การสร้างและแชร์บัตรฉุกเฉินของคุณคือก้าวสำคัญแรกสู่การดำน้ำที่ปลอดภัยยิ่งขึ้น",
    nl: "Bedankt voor het gebruiken van de tool. Het maken en delen van je noodkaart is de eerste belangrijke stap naar een veiligere duik.",
    pl: "Dziękujemy za korzystanie z narzędzia. Utworzenie i udostępnienie karty awaryjnej to pierwszy ważny krok do bezpieczniejszego nurkowania."
  },
  deco_beer_support: {
    zh: "如果你愿意请开发者喝一杯 Deco Beer，可以在这里支持：",
    hi: "यदि आप डेवलपर को एक Deco Beer देना चाहते हैं, तो यहाँ कर सकते हैं:",
    pt: "Se quiser pagar uma Deco Beer ao desenvolvedor, você pode fazer isso aqui:",
    id: "Jika Anda ingin mentraktir pengembang dengan Deco Beer, Anda bisa melakukannya di sini:",
    ru: "Если вы хотите угостить разработчика Deco Beer, вы можете сделать это здесь:",
    ja: "開発者に Deco Beer をおごりたい場合は、こちらからどうぞ：",
    vi: "Nếu bạn muốn mời nhà phát triển một Deco Beer, bạn có thể thực hiện tại đây:",
    tr: "Geliştiriciye bir Deco Beer ısmarlamak isterseniz bunu burada yapabilirsiniz:",
    tl: "Kung gusto mong ilibre ang developer ng Deco Beer, puwede mo itong gawin dito:",
    ko: "개발자에게 Deco Beer를 한 잔 사고 싶다면 여기에서 할 수 있습니다:",
    th: "หากคุณอยากเลี้ยง Deco Beer ให้ผู้พัฒนา คุณสามารถทำได้ที่นี่:",
    nl: "Als je de ontwikkelaar een Deco Beer wilt geven, kun je dat hier doen:",
    pl: "Jeśli chcesz postawić deweloperowi Deco Beer, możesz to zrobić tutaj:"
  }
});

Object.assign(window.SafeDiveCardLanguagePacks.raw, {
  zh: {
    "Diver": "潜水员",
    "Remove Diver": "移除潜水员",
    "Full Name": "全名",
    "Sex": "性别",
    "Birth Date": "出生日期",
    "Dive Count": "潜水次数",
    "Certifications (comma separated)": "认证（逗号分隔）",
    "Breathing Gas": "呼吸气体",
    "Other Breathing Gas": "其他呼吸气体",
    "Allergies (comma separated)": "过敏（逗号分隔）",
    "Medical Conditions (comma separated)": "病史（逗号分隔）",
    "Medications (comma separated)": "药物（逗号分隔）",
    "Health Insurance Provider": "医疗保险提供方",
    "Dive Insurance Provider": "潜水保险提供方",
    "Dive Insurance Member No": "潜水保险会员号",
    "Dive Insurance Hotline": "潜水保险热线",
    "Emergency Contact Name": "紧急联系人姓名",
    "Emergency Contact Relation": "紧急联系人关系",
    "Emergency Contact Phone": "紧急联系电话",
    "Divers in Group": "团队潜水员人数",
    "Who (cont.)": "人员（续）",
    "Birth / Age": "出生 / 年龄",
    "Emergency Contact": "紧急联系人",
    "Dive Insurance": "潜水保险",
    "Own Contact": "本人联系方式",
    "Divers": "潜水员",
    "Other...": "其他..."
  },
  hi: {
    "Diver": "डाइवर",
    "Remove Diver": "डाइवर हटाएँ",
    "Full Name": "पूरा नाम",
    "Sex": "लिंग",
    "Birth Date": "जन्म तिथि",
    "Dive Count": "डाइव संख्या",
    "Certifications (comma separated)": "प्रमाणपत्र (कॉमा से अलग)",
    "Breathing Gas": "सांस लेने की गैस",
    "Other Breathing Gas": "अन्य सांस लेने की गैस",
    "Allergies (comma separated)": "एलर्जी (कॉमा से अलग)",
    "Medical Conditions (comma separated)": "चिकित्सीय स्थितियाँ (कॉमा से अलग)",
    "Medications (comma separated)": "दवाएँ (कॉमा से अलग)",
    "Health Insurance Provider": "स्वास्थ्य बीमा प्रदाता",
    "Dive Insurance Provider": "डाइव बीमा प्रदाता",
    "Dive Insurance Member No": "डाइव बीमा सदस्य संख्या",
    "Dive Insurance Hotline": "डाइव बीमा हॉटलाइन",
    "Emergency Contact Name": "आपातकालीन संपर्क नाम",
    "Emergency Contact Relation": "आपात संपर्क संबंध",
    "Emergency Contact Phone": "आपात संपर्क फोन",
    "Divers in Group": "समूह में डाइवर्स",
    "Who (cont.)": "कौन (जारी)",
    "Birth / Age": "जन्म / आयु",
    "Emergency Contact": "आपात संपर्क",
    "Dive Insurance": "डाइव बीमा",
    "Own Contact": "स्वयं संपर्क",
    "Divers": "डाइवर्स",
    "Other...": "अन्य..."
  },
  pt: {
    "Diver": "Mergulhador",
    "Remove Diver": "Remover mergulhador",
    "Full Name": "Nome completo",
    "Sex": "Sexo",
    "Birth Date": "Data de nascimento",
    "Dive Count": "Número de mergulhos",
    "Certifications (comma separated)": "Certificações (separadas por vírgula)",
    "Breathing Gas": "Gás respiratório",
    "Other Breathing Gas": "Outro gás respiratório",
    "Allergies (comma separated)": "Alergias (separadas por vírgula)",
    "Medical Conditions (comma separated)": "Condições médicas (separadas por vírgula)",
    "Medications (comma separated)": "Medicamentos (separados por vírgula)",
    "Health Insurance Provider": "Seguradora de saúde",
    "Dive Insurance Provider": "Fornecedor do seguro de mergulho",
    "Dive Insurance Member No": "Número de membro do seguro de mergulho",
    "Dive Insurance Hotline": "Hotline do seguro de mergulho",
    "Emergency Contact Name": "Nome do contato de emergência",
    "Emergency Contact Relation": "Relação do contato de emergência",
    "Emergency Contact Phone": "Telefone do contato de emergência",
    "Divers in Group": "Mergulhadores no grupo",
    "Who (cont.)": "Quem (cont.)",
    "Birth / Age": "Nascimento / Idade",
    "Emergency Contact": "Contato de emergência",
    "Dive Insurance": "Seguro de mergulho",
    "Own Contact": "Contato próprio",
    "Divers": "Mergulhadores",
    "Other...": "Outro..."
  },
  id: {
    "Diver": "Penyelam",
    "Remove Diver": "Hapus penyelam",
    "Full Name": "Nama lengkap",
    "Sex": "Jenis kelamin",
    "Birth Date": "Tanggal lahir",
    "Dive Count": "Jumlah penyelaman",
    "Certifications (comma separated)": "Sertifikasi (dipisahkan koma)",
    "Breathing Gas": "Gas pernapasan",
    "Other Breathing Gas": "Gas pernapasan lain",
    "Allergies (comma separated)": "Alergi (dipisahkan koma)",
    "Medical Conditions (comma separated)": "Kondisi medis (dipisahkan koma)",
    "Medications (comma separated)": "Obat-obatan (dipisahkan koma)",
    "Health Insurance Provider": "Penyedia asuransi kesehatan",
    "Dive Insurance Provider": "Penyedia asuransi selam",
    "Dive Insurance Member No": "Nomor anggota asuransi selam",
    "Dive Insurance Hotline": "Hotline asuransi selam",
    "Emergency Contact Name": "Nama kontak darurat",
    "Emergency Contact Relation": "Hubungan kontak darurat",
    "Emergency Contact Phone": "Telepon kontak darurat",
    "Divers in Group": "Penyelam dalam grup",
    "Who (cont.)": "Siapa (lanj.)",
    "Birth / Age": "Lahir / Usia",
    "Emergency Contact": "Kontak darurat",
    "Dive Insurance": "Asuransi selam",
    "Own Contact": "Kontak sendiri",
    "Divers": "Penyelam",
    "Other...": "Lainnya..."
  }
});

Object.assign(window.SafeDiveCardLanguagePacks.raw, {
  pl: {
    "Diver": "Nurek",
    "Remove Diver": "Usuń nurka",
    "Full Name": "Imię i nazwisko",
    "Sex": "Płeć",
    "Birth Date": "Data urodzenia",
    "Dive Count": "Liczba nurkowań",
    "Certifications (comma separated)": "Certyfikaty (oddzielone przecinkami)",
    "Breathing Gas": "Gaz oddechowy",
    "Other Breathing Gas": "Inny gaz oddechowy",
    "Allergies (comma separated)": "Alergie (oddzielone przecinkami)",
    "Medical Conditions (comma separated)": "Choroby przewlekłe (oddzielone przecinkami)",
    "Medications (comma separated)": "Leki (oddzielone przecinkami)",
    "Health Insurance Provider": "Ubezpieczyciel zdrowotny",
    "Dive Insurance Provider": "Ubezpieczyciel nurkowy",
    "Dive Insurance Member No": "Numer członkowski ubezpieczenia nurkowego",
    "Dive Insurance Hotline": "Infolinia ubezpieczenia nurkowego",
    "Emergency Contact Name": "Imię kontaktu alarmowego",
    "Emergency Contact Relation": "Relacja kontaktu alarmowego",
    "Emergency Contact Phone": "Telefon kontaktu alarmowego",
    "Divers in Group": "Nurkowie w grupie",
    "Who (cont.)": "Kto (cd.)",
    "Birth / Age": "Urodzenie / Wiek",
    "Emergency Contact": "Kontakt alarmowy",
    "Dive Insurance": "Ubezpieczenie nurkowe",
    "Own Contact": "Własny kontakt",
    "Divers": "Nurkowie",
    "Other...": "Inne..."
  }
});

Object.assign(window.SafeDiveCardLanguagePacks.raw, {
  tl: {
    "Diver": "Diver",
    "Remove Diver": "Alisin ang diver",
    "Full Name": "Buong pangalan",
    "Sex": "Kasarian",
    "Birth Date": "Petsa ng kapanganakan",
    "Dive Count": "Bilang ng dive",
    "Certifications (comma separated)": "Mga sertipikasyon (pinaghiwalay ng kuwit)",
    "Breathing Gas": "Breathing gas",
    "Other Breathing Gas": "Ibang breathing gas",
    "Allergies (comma separated)": "Mga allergy (pinaghiwalay ng kuwit)",
    "Medical Conditions (comma separated)": "Mga kondisyong medikal (pinaghiwalay ng kuwit)",
    "Medications (comma separated)": "Mga gamot (pinaghiwalay ng kuwit)",
    "Health Insurance Provider": "Provider ng health insurance",
    "Dive Insurance Provider": "Provider ng dive insurance",
    "Dive Insurance Member No": "Member no. ng dive insurance",
    "Dive Insurance Hotline": "Hotline ng dive insurance",
    "Emergency Contact Name": "Pangalan ng emergency contact",
    "Emergency Contact Relation": "Relasyon ng emergency contact",
    "Emergency Contact Phone": "Telepono ng emergency contact",
    "Divers in Group": "Mga diver sa grupo",
    "Who (cont.)": "Sino (tuloy)",
    "Birth / Age": "Kapanganakan / Edad",
    "Emergency Contact": "Emergency contact",
    "Dive Insurance": "Dive insurance",
    "Own Contact": "Sariling contact",
    "Divers": "Mga diver",
    "Other...": "Iba pa..."
  },
  ko: {
    "Diver": "다이버",
    "Remove Diver": "다이버 제거",
    "Full Name": "성명",
    "Sex": "성별",
    "Birth Date": "생년월일",
    "Dive Count": "다이빙 횟수",
    "Certifications (comma separated)": "자격증(쉼표로 구분)",
    "Breathing Gas": "호흡 가스",
    "Other Breathing Gas": "기타 호흡 가스",
    "Allergies (comma separated)": "알레르기(쉼표로 구분)",
    "Medical Conditions (comma separated)": "의학적 상태(쉼표로 구분)",
    "Medications (comma separated)": "복용약(쉼표로 구분)",
    "Health Insurance Provider": "건강보험 제공자",
    "Dive Insurance Provider": "다이빙 보험 제공자",
    "Dive Insurance Member No": "다이빙 보험 회원 번호",
    "Dive Insurance Hotline": "다이빙 보험 핫라인",
    "Emergency Contact Name": "비상 연락처 이름",
    "Emergency Contact Relation": "비상 연락처 관계",
    "Emergency Contact Phone": "비상 연락처 전화번호",
    "Divers in Group": "그룹 내 다이버 수",
    "Who (cont.)": "누구 (계속)",
    "Birth / Age": "출생 / 나이",
    "Emergency Contact": "비상 연락처",
    "Dive Insurance": "다이빙 보험",
    "Own Contact": "본인 연락처",
    "Divers": "다이버",
    "Other...": "기타..."
  },
  th: {
    "Diver": "นักดำน้ำ",
    "Remove Diver": "ลบนักดำน้ำ",
    "Full Name": "ชื่อเต็ม",
    "Sex": "เพศ",
    "Birth Date": "วันเกิด",
    "Dive Count": "จำนวนการดำน้ำ",
    "Certifications (comma separated)": "ใบรับรอง (คั่นด้วยจุลภาค)",
    "Breathing Gas": "ก๊าซหายใจ",
    "Other Breathing Gas": "ก๊าซหายใจอื่น",
    "Allergies (comma separated)": "อาการแพ้ (คั่นด้วยจุลภาค)",
    "Medical Conditions (comma separated)": "โรคประจำตัว (คั่นด้วยจุลภาค)",
    "Medications (comma separated)": "ยา (คั่นด้วยจุลภาค)",
    "Health Insurance Provider": "ผู้ให้บริการประกันสุขภาพ",
    "Dive Insurance Provider": "ผู้ให้บริการประกันดำน้ำ",
    "Dive Insurance Member No": "หมายเลขสมาชิกประกันดำน้ำ",
    "Dive Insurance Hotline": "สายด่วนประกันดำน้ำ",
    "Emergency Contact Name": "ชื่อผู้ติดต่อฉุกเฉิน",
    "Emergency Contact Relation": "ความสัมพันธ์ของผู้ติดต่อฉุกเฉิน",
    "Emergency Contact Phone": "โทรศัพท์ผู้ติดต่อฉุกเฉิน",
    "Divers in Group": "นักดำน้ำในกลุ่ม",
    "Who (cont.)": "ใคร (ต่อ)",
    "Birth / Age": "วันเกิด / อายุ",
    "Emergency Contact": "ผู้ติดต่อฉุกเฉิน",
    "Dive Insurance": "ประกันดำน้ำ",
    "Own Contact": "ข้อมูลติดต่อของตนเอง",
    "Divers": "นักดำน้ำ",
    "Other...": "อื่น ๆ..."
  },
  nl: {
    "Diver": "Duiker",
    "Remove Diver": "Duiker verwijderen",
    "Full Name": "Volledige naam",
    "Sex": "Geslacht",
    "Birth Date": "Geboortedatum",
    "Dive Count": "Aantal duiken",
    "Certifications (comma separated)": "Certificeringen (kommagescheiden)",
    "Breathing Gas": "Ademgas",
    "Other Breathing Gas": "Ander ademgas",
    "Allergies (comma separated)": "Allergieën (kommagescheiden)",
    "Medical Conditions (comma separated)": "Medische aandoeningen (kommagescheiden)",
    "Medications (comma separated)": "Medicatie (kommagescheiden)",
    "Health Insurance Provider": "Zorgverzekeraar",
    "Dive Insurance Provider": "Duikverzekeraar",
    "Dive Insurance Member No": "Lidnummer duikverzekering",
    "Dive Insurance Hotline": "Hotline duikverzekering",
    "Emergency Contact Name": "Naam noodcontact",
    "Emergency Contact Relation": "Relatie noodcontact",
    "Emergency Contact Phone": "Telefoon noodcontact",
    "Divers in Group": "Duikers in de groep",
    "Who (cont.)": "Wie (vervolg)",
    "Birth / Age": "Geboorte / Leeftijd",
    "Emergency Contact": "Noodcontact",
    "Dive Insurance": "Duikverzekering",
    "Own Contact": "Eigen contact",
    "Divers": "Duikers",
    "Other...": "Anders..."
  }
});

Object.assign(window.SafeDiveCardLanguagePacks.raw, {
  ru: {
    "Diver": "Дайвер",
    "Remove Diver": "Удалить дайвера",
    "Full Name": "Полное имя",
    "Sex": "Пол",
    "Birth Date": "Дата рождения",
    "Dive Count": "Количество погружений",
    "Certifications (comma separated)": "Сертификаты (через запятую)",
    "Breathing Gas": "Газ для дыхания",
    "Other Breathing Gas": "Другой дыхательный газ",
    "Allergies (comma separated)": "Аллергии (через запятую)",
    "Medical Conditions (comma separated)": "Медицинские состояния (через запятую)",
    "Medications (comma separated)": "Лекарства (через запятую)",
    "Health Insurance Provider": "Поставщик медстраховки",
    "Dive Insurance Provider": "Поставщик страховки дайвера",
    "Dive Insurance Member No": "Номер страховки дайвера",
    "Dive Insurance Hotline": "Горячая линия страховки дайвера",
    "Emergency Contact Name": "Имя экстренного контакта",
    "Emergency Contact Relation": "Связь с экстренным контактом",
    "Emergency Contact Phone": "Телефон экстренного контакта",
    "Divers in Group": "Дайверов в группе",
    "Who (cont.)": "Кто (прод.)",
    "Birth / Age": "Рождение / Возраст",
    "Emergency Contact": "Экстренный контакт",
    "Dive Insurance": "Страховка дайвера",
    "Own Contact": "Свой контакт",
    "Divers": "Дайверы",
    "Other...": "Другое..."
  },
  ja: {
    "Diver": "ダイバー",
    "Remove Diver": "ダイバーを削除",
    "Full Name": "氏名",
    "Sex": "性別",
    "Birth Date": "生年月日",
    "Dive Count": "潜水本数",
    "Certifications (comma separated)": "資格（カンマ区切り）",
    "Breathing Gas": "呼吸ガス",
    "Other Breathing Gas": "その他の呼吸ガス",
    "Allergies (comma separated)": "アレルギー（カンマ区切り）",
    "Medical Conditions (comma separated)": "既往症（カンマ区切り）",
    "Medications (comma separated)": "服用薬（カンマ区切り）",
    "Health Insurance Provider": "健康保険会社",
    "Dive Insurance Provider": "ダイビング保険会社",
    "Dive Insurance Member No": "ダイビング保険会員番号",
    "Dive Insurance Hotline": "ダイビング保険ホットライン",
    "Emergency Contact Name": "緊急連絡先氏名",
    "Emergency Contact Relation": "緊急連絡先との関係",
    "Emergency Contact Phone": "緊急連絡先電話番号",
    "Divers in Group": "グループのダイバー数",
    "Who (cont.)": "誰（続き）",
    "Birth / Age": "生年月日 / 年齢",
    "Emergency Contact": "緊急連絡先",
    "Dive Insurance": "ダイビング保険",
    "Own Contact": "本人連絡先",
    "Divers": "ダイバー",
    "Other...": "その他..."
  },
  vi: {
    "Diver": "Thợ lặn",
    "Remove Diver": "Xóa thợ lặn",
    "Full Name": "Họ và tên",
    "Sex": "Giới tính",
    "Birth Date": "Ngày sinh",
    "Dive Count": "Số lần lặn",
    "Certifications (comma separated)": "Chứng chỉ (ngăn cách bằng dấu phẩy)",
    "Breathing Gas": "Khí thở",
    "Other Breathing Gas": "Khí thở khác",
    "Allergies (comma separated)": "Dị ứng (ngăn cách bằng dấu phẩy)",
    "Medical Conditions (comma separated)": "Tình trạng y tế (ngăn cách bằng dấu phẩy)",
    "Medications (comma separated)": "Thuốc (ngăn cách bằng dấu phẩy)",
    "Health Insurance Provider": "Nhà cung cấp bảo hiểm y tế",
    "Dive Insurance Provider": "Nhà cung cấp bảo hiểm lặn",
    "Dive Insurance Member No": "Số thành viên bảo hiểm lặn",
    "Dive Insurance Hotline": "Đường dây nóng bảo hiểm lặn",
    "Emergency Contact Name": "Tên liên hệ khẩn cấp",
    "Emergency Contact Relation": "Mối quan hệ liên hệ khẩn cấp",
    "Emergency Contact Phone": "Điện thoại liên hệ khẩn cấp",
    "Divers in Group": "Số thợ lặn trong nhóm",
    "Who (cont.)": "Ai (tiếp)",
    "Birth / Age": "Ngày sinh / Tuổi",
    "Emergency Contact": "Liên hệ khẩn cấp",
    "Dive Insurance": "Bảo hiểm lặn",
    "Own Contact": "Liên hệ của mình",
    "Divers": "Thợ lặn",
    "Other...": "Khác..."
  },
  tr: {
    "Diver": "Dalgıç",
    "Remove Diver": "Dalgıcı kaldır",
    "Full Name": "Ad soyad",
    "Sex": "Cinsiyet",
    "Birth Date": "Doğum tarihi",
    "Dive Count": "Dalış sayısı",
    "Certifications (comma separated)": "Sertifikalar (virgülle ayrılmış)",
    "Breathing Gas": "Solunum gazı",
    "Other Breathing Gas": "Diğer solunum gazı",
    "Allergies (comma separated)": "Alerjiler (virgülle ayrılmış)",
    "Medical Conditions (comma separated)": "Tıbbi durumlar (virgülle ayrılmış)",
    "Medications (comma separated)": "İlaçlar (virgülle ayrılmış)",
    "Health Insurance Provider": "Sağlık sigortası sağlayıcısı",
    "Dive Insurance Provider": "Dalış sigortası sağlayıcısı",
    "Dive Insurance Member No": "Dalış sigortası üye no",
    "Dive Insurance Hotline": "Dalış sigortası hattı",
    "Emergency Contact Name": "Acil durum kişi adı",
    "Emergency Contact Relation": "Acil durum kişi ilişkisi",
    "Emergency Contact Phone": "Acil durum kişi telefonu",
    "Divers in Group": "Gruptaki dalgıç sayısı",
    "Who (cont.)": "Kim (devam)",
    "Birth / Age": "Doğum / Yaş",
    "Emergency Contact": "Acil durum kişisi",
    "Dive Insurance": "Dalış sigortası",
    "Own Contact": "Kendi iletişimi",
    "Divers": "Dalgıçlar",
    "Other...": "Diğer..."
  }
});
